### ISSUE TITLE
How to create a new dictionary and add phones that don't exist

### ISSUE THREAD

**Issue by psubhashish** [alexram1313/text-to-speech-sample#2]
Hi, first of all thank you so very much for making this so simpler. I'm no geek but I'm trying to toy with this tool and am trying to create one for my own language [Odia](https://en.wikipedia.org/wiki/Odia_language). However the dictionary would be totally different because the Odia language has different phonemes. Can you please explain in a step-by-step manner about creating a dictionary for a non-Latin-alphabet-based language? Thanks in advance.

**Comment by alexram1313** [comment]
Since the alphabet of Odia uses non-ASCII (Latin alphabet used in the US) characters, the script itself will not work instantaneously; however, that does not mean you can't make it work.

First, instead of using the ARPAbet dictionary file included in this repository, try finding or making your own pronunciation dictionary file for Odia. If you need to create your own dictionary, take a look at the IPA for standard notations for sounds.

Second, on <a href="https://github.com/alexram1313/text-to-speech-sample/blob/master/load.py#L18">line 18 of load.py</a>, make it so that it reads:
`with open(words_pron_dict, mode = 'r', encoding='utf-8') as file`
This will allow you to handle Odia characters in <a href="http://unicode.org/charts/PDF/U0B00.pdf">Unicode</a>. When you print, you might see something like '\u0B15' but that is simply the ASCII representation of a valid character. You might also need to input all your strings like that too.

Hope this helps!

**Comment by psubhashish** [comment]
Thanks for the quick comment.

1. We have created an [Odia->IPA converter ](https://or.wikipedia.org/s/14kh) a while back but I don't know how to create the ARPAbet dictionary (which does not exist for Odia). Will really appreciate if you can share how to create that and about the way to construct a dictionary like [this](https://github.com/OdiaWikimedia/Lekatha/blob/master/English/cmudict-0.7b.txt?raw=true) will be really great.

2. I have made the [changes](https://github.com/OdiaWikimedia/Lekatha/blob/master/load.py#L18) in the code as you suggested. Do let me know if that is correct or not.

**Comment by alexram1313** [comment]
1. So the ARPAbet dictionary is basically a collection of every word next to a representation of the word's pronunciation (e.g., for the word "apple", the entry reads: APPLE  AE1 P AH0 L ). You would need to list every known Odia word with a sequence of relevant characters representation its pronunciation to the right. This might need to be a manual process of literally finding a dictionary and converting every word to IPA, though I'm sure there's an easier way to do it.

2. Looks good. I also forgot to mention that on line 22, the use of regular expressions won't work if you're going to use IPA. The reason for the RegEx is since the script cannot determine the correct version of a word that is a homophone based on context. I am not sure if homophones are common in Odia but if they aren't, you can simply remove any use of the `re` module and leave the pronunciation as a `str`. I'm not entirely sure how to handle homophones if needed.

**Comment by psubhashish** [comment]
1. Probably need to create a converter to do that in a bulk manner. I have a couple of questions here:
a. Can I map the Odia characters in a standard that is not similar to the dictionary you have provided? See an [example](https://docs.google.com/spreadsheets/d/1mjCJJO_nYToo6LoEtySWNMPJ7DrJ3XR1_dy_M3R8ZzQ/edit?usp=sharing) (the "Odia mapping" sheet).
b. Are three different stress levels like AE0, AE1 and AE2 recorded separately?
c. Can we add new rules for three more—affirmative (phoneme ending with a period), question (phoneme ending with a question mark, and exclaimatory (phoneme ending with an exclamation mark)?
2. AFAIK, Odia does not have homophones but I am not very sure. BTW I don't know if it would be easier to use IPA. But if that would be possible then we can easily create a dictionary for Odia. I quite did not get how to do that in your 2nd reply.

**Comment by psubhashish** [comment]
Hi @alexram1313, I was experimenting by mapping the Odia characters and it worked for a moment but stopped after that. It looks like the below now.
<img width="625" alt="new issue" src="https://cloud.githubusercontent.com/assets/1258090/26553118/d997e830-44a7-11e7-813f-bd1ae98041c8.png">

**Comment by alexram1313** [comment]
Wow! Since you already have that sort of mapping, those that in your dictionary file instead of IPA. In this case, you wouldn't need to remove `re` as I suggested before. As for variations before punctuations, the script as is does not know how to handle it but I'm sure there's a way.

It seems something is wrong with your data. Make sure every line follows this format:
Word(space)(space)sound1(space)sound2(space)...(space)soundn

**Comment by psubhashish** [comment]
Not sure what could be the mistake. I have mapped all the words with the corresponding sound files. See all of them below.
![screen shot 2017-05-30 at 12 12 15 pm](https://cloud.githubusercontent.com/assets/1258090/26570869/5e41a84a-4530-11e7-9937-21c48e7be712.png)

**Comment by alexram1313** [comment]
My mistake. There should be 2 spaces in the beginning. I've edited the previous reply to reflect the changes.

**Comment by psubhashish** [comment]
It worked. Thanks much again. I cannot appreciate you much for your kind support. Now I have another issue—sounds are superimposing on each other. The independent vowels/consonants sound fine. But when I try to combine phonemes to make a syllable, it just does not work. The sounds are superimposed. The synthesized sounds are [here](https://github.com/OdiaWikimedia/Lekatha/tree/master/synthesized%20samples) and the phonemes are [here](https://github.com/OdiaWikimedia/Lekatha/tree/master/sounds)

**Comment by psubhashish** [comment]
It worked. Thanks much again. I cannot appreciate you much for your kind support. Now I have another issue—sounds are superimposing on each other. The independent vowels/consonants sound fine. But when I try to combine phonemes to make a syllable, it just does not work. The sounds are superimposed. The synthesized sounds are [here](https://github.com/OdiaWikimedia/Lekatha/tree/master/synthesized%20samples) and the phonemes are [here](https://github.com/OdiaWikimedia/Lekatha/tree/master/sounds)

**Comment by alexram1313** [comment]
This might due to the delay not being correct for the language. On <a href="https://github.com/alexram1313/text-to-speech-sample/blob/master/load.py#L33">line 33</a>, we add to an arbitrary delay to wait that many seconds from the start before playing that certain sound. Play around with that value to see what you get. 

And I'm glad to help! 😄

**Comment by psubhashish** [comment]
I have finally managed to create a [converter](url) (it's not complete yet) that converts Odia text into LATIN and T RA NS K R I P SH AH N. However, I need to manually create the text file. I am curious if there is a way to generate a text file which would take a long list of Odia words and will generate a text file having each word in the following format:

<code>କଥା (Odia word)[space][space]LATIN_WORD[space][space]T RA NS K R I P SH AH N</code>

BTW here is the [output](https://commons.wikimedia.org/wiki/OpenSpeaks/toolkit/Lekatha#Test_run) from the first batch of test run.

**Comment by alexram1313** [comment]
That's amazing! 😮 

You could write a script that iterates through each word, gets the corresponding representations through some libraries or custom functions, then writes the whole thing into a text file.
